/-
This file is generated by scripts/export_data.py. Do not edit it by hand.
The absolute --source-root is intentionally omitted so identical pinned inputs
produce identical output on every machine.

Pinned sources:
* Hadamard-T/data/T103.json
  SHA-256: cf59cb40fcdc74f9309161ad2d50ddd7ad462446da365efb527de0dd4e295a06
* Hadamard-T/data/T163.json
  SHA-256: 285557b7fc0f846af4fcec2e83d5d97eabcff3b82b2171bd0a6bdf32f8d27a4d
* Hadamard-T/data/williamson-quadruples.json
  SHA-256: 515dac963269e31694445c5ad7635b001e16b3ea3cdb58fa8ee12eaae47e0446
* Hadamard-T/data/williamson-13.json
  SHA-256: 249ba0919c5f0b82faab5d6c248a1a2ab18107d5a6ee2175195236fc3509935f
-/

import HadamardFormal.Defs

namespace HadamardFormal.Data

open HadamardFormalCore

private def t103Data : Vector (Vector Int 103) 4 :=
  #v[
    #v[
      0, 0, 0, -1, 0, -1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
      0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 1,
      0, 0, 1, -1, 0, 0, 0, 0, -1, 0, 1, 0, -1, 0, 0, 0,
      0, -1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, -1, -1, -1, 0, 0, 1, 0, 0, 0, -1, -1, 0, -1, 1, 0,
      -1, 0, 0, 1, 0, 0, 1, 1, 1, -1, 0, -1, 0, 0, 0, -1,
      0, 0, 0, 0, 0, 0, 0
    ],
    #v[
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1, 0,
      0, -1, 0, 0, 0, 0, 1, -1, 0, -1, 1, 0, -1, 0, 0, 0,
      0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -1, 0, 0,
      -1, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 1, -1, -1, 1,
      1, 0, 0, 0, -1, -1, 0, -1, 0, -1, 0, 0, 1, 0, 0, 0,
      0, 0, 1, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 1, 0, 1, -1, 0, 0
    ],
    #v[
      1, 0, -1, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
      1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1,
      0, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 0,
      0, 0, 1, 0, 0, 1, -1
    ],
    #v[
      0, -1, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 1,
      1, 0, 1, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 1, 0, 0, -1, 0,
      0, 0, 0, 0, 0, 0, 0, -1, -1, 0, -1, -1, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0,
      -1, 0, 0, 0, 0, 0, 0
    ]
  ]

/-- The generated four-sequence T-matrix witness of order 103. -/
def t103 : Fin 4 → Fin 103 → Int := fun i j =>
  (t103Data.get i).get j

private def t163Data : Vector (Vector Int 163) 4 :=
  #v[
    #v[
      1, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 1, -1, 0, 0, 1,
      0, 0, -1, 1, 1, -1, -1, -1, 1, -1, 0, 0, 0, 1, -1, 0,
      -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, -1, 0, 0, 0,
      0, 0, -1, 1, 1, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, -1,
      0, -1, -1, 0, -1, 0, 1, 0, 0, 1, 0, -1, 0, -1, -1, -1,
      0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
      0, 1, 0, 0, 1, 0, 0, 0, 0, -1, 0, -1, 1, 0, -1, 1,
      -1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 1, -1, 0, 0,
      0, -1, -1, 1, 0, 0, 1, -1, 0, 0, 0, -1, 0, 0, 0, 1,
      1, 1, -1, -1, 1, 1, 0, 0, 0, 0, -1, -1, 0, 0, 0, 1,
      0, 0, -1
    ],
    #v[
      0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 1, 0, -1, 0, -1, 0, 0, 1, 0, 0, 0, 0,
      0, 1, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0,
      1, 0, 0, -1, 0, 1, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0,
      0, 0, 0, 1, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1, 0,
      -1, 0, 0, 0, 1, -1, 0, 0, 1, -1, 0, 0, -1, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 1, 0, 1, -1, 0, 0, 0, 0, 1, 0,
      1, 0, 0
    ],
    #v[
      0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
      0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, -1, -1,
      1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 1, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
      0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0, 0, 0,
      1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0,
      0, -1, 0
    ],
    #v[
      0, 0, -1, 0, 0, 0, 0, -1, 1, 1, 0, 0, 0, 0, 0, 0,
      1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
      0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0,
      -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0, 0, 0, 0,
      0, 1, 0, 0, -1, -1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
      0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
      0, 0, 0
    ]
  ]

/-- The generated four-sequence T-matrix witness of order 163. -/
def t163 : Fin 4 → Fin 163 → Int := fun i j =>
  (t163Data.get i).get j

private def w7Data : Vector (Vector Int 7) 4 :=
  #v[
    #v[
      1, 1, 1, -1, -1, 1, 1
    ],
    #v[
      1, 1, 1, -1, -1, 1, 1
    ],
    #v[
      1, 1, -1, 1, 1, -1, 1
    ],
    #v[
      1, -1, 1, -1, -1, 1, -1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 7. -/
def w7 : Fin 4 → Fin 7 → Int := fun i j =>
  (w7Data.get i).get j

private def w11Data : Vector (Vector Int 11) 4 :=
  #v[
    #v[
      1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1
    ],
    #v[
      1, -1, 1, 1, 1, -1, -1, 1, 1, 1, -1
    ],
    #v[
      1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1
    ],
    #v[
      1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 11. -/
def w11 : Fin 4 → Fin 11 → Int := fun i j =>
  (w11Data.get i).get j

private def w13Data : Vector (Vector Int 13) 4 :=
  #v[
    #v[
      1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1
    ],
    #v[
      1, 1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1
    ],
    #v[
      -1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1
    ],
    #v[
      1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 13. -/
def w13 : Fin 4 → Fin 13 → Int := fun i j =>
  (w13Data.get i).get j

private def w17Data : Vector (Vector Int 17) 4 :=
  #v[
    #v[
      -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1, -1,
      1
    ],
    #v[
      -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1,
      1
    ],
    #v[
      1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, 1, -1, 1,
      1
    ],
    #v[
      -1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, 1, 1,
      1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 17. -/
def w17 : Fin 4 → Fin 17 → Int := fun i j =>
  (w17Data.get i).get j

private def w19Data : Vector (Vector Int 19) 4 :=
  #v[
    #v[
      -1, 1, -1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1,
      1, -1, 1
    ],
    #v[
      1, 1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1,
      -1, -1, 1
    ],
    #v[
      -1, 1, 1, 1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, 1,
      1, 1, 1
    ],
    #v[
      -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, 1,
      -1, 1, 1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 19. -/
def w19 : Fin 4 → Fin 19 → Int := fun i j =>
  (w19Data.get i).get j

private def w23Data : Vector (Vector Int 23) 4 :=
  #v[
    #v[
      -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1,
      -1, -1, 1, 1, 1, 1, 1
    ],
    #v[
      1, 1, -1, 1, -1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1,
      1, 1, 1, -1, 1, -1, 1
    ],
    #v[
      1, 1, 1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1,
      -1, -1, -1, 1, 1, 1, 1
    ],
    #v[
      1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1,
      1, 1, -1, -1, 1, -1, 1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 23. -/
def w23 : Fin 4 → Fin 23 → Int := fun i j =>
  (w23Data.get i).get j

private def w29Data : Vector (Vector Int 29) 4 :=
  #v[
    #v[
      1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1, 1, -1, 1, 1, 1,
      1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1
    ],
    #v[
      1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1, -1,
      -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1
    ],
    #v[
      1, 1, 1, -1, -1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1, -1,
      -1, -1, 1, 1, -1, 1, -1, 1, 1, -1, -1, 1, 1
    ],
    #v[
      -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1,
      1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1
    ]
  ]

/-- The generated symmetric Williamson four-sequence witness of order 29. -/
def w29 : Fin 4 → Fin 29 → Int := fun i j =>
  (w29Data.get i).get j

-- The kernel checks below evaluate fixed-length integer
-- autocorrelation sums; the raised limits apply to this
-- generated file only, and the style linter for file-level
-- options is disabled here for the generated literals.
set_option linter.style.setOption false
set_option maxRecDepth 100000
set_option maxHeartbeats 0

private theorem t103_entries : ∀ i q, IsTEntry (t103 i q) := by
  decide

private theorem t103_support : ∀ q, supportCount t103 q = 1 := by
  decide

private theorem t103_paf_0 :
    (∑ i, paf (t103 i) (⟨0, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨0, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_1 :
    (∑ i, paf (t103 i) (⟨1, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨1, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_2 :
    (∑ i, paf (t103 i) (⟨2, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨2, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_3 :
    (∑ i, paf (t103 i) (⟨3, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨3, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_4 :
    (∑ i, paf (t103 i) (⟨4, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨4, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_5 :
    (∑ i, paf (t103 i) (⟨5, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨5, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_6 :
    (∑ i, paf (t103 i) (⟨6, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨6, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_7 :
    (∑ i, paf (t103 i) (⟨7, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨7, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_8 :
    (∑ i, paf (t103 i) (⟨8, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨8, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_9 :
    (∑ i, paf (t103 i) (⟨9, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨9, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_10 :
    (∑ i, paf (t103 i) (⟨10, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨10, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_11 :
    (∑ i, paf (t103 i) (⟨11, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨11, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_12 :
    (∑ i, paf (t103 i) (⟨12, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨12, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_13 :
    (∑ i, paf (t103 i) (⟨13, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨13, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_14 :
    (∑ i, paf (t103 i) (⟨14, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨14, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_15 :
    (∑ i, paf (t103 i) (⟨15, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨15, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_16 :
    (∑ i, paf (t103 i) (⟨16, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨16, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_17 :
    (∑ i, paf (t103 i) (⟨17, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨17, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_18 :
    (∑ i, paf (t103 i) (⟨18, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨18, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_19 :
    (∑ i, paf (t103 i) (⟨19, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨19, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_20 :
    (∑ i, paf (t103 i) (⟨20, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨20, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_21 :
    (∑ i, paf (t103 i) (⟨21, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨21, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_22 :
    (∑ i, paf (t103 i) (⟨22, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨22, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_23 :
    (∑ i, paf (t103 i) (⟨23, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨23, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_24 :
    (∑ i, paf (t103 i) (⟨24, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨24, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_25 :
    (∑ i, paf (t103 i) (⟨25, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨25, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_26 :
    (∑ i, paf (t103 i) (⟨26, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨26, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_27 :
    (∑ i, paf (t103 i) (⟨27, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨27, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_28 :
    (∑ i, paf (t103 i) (⟨28, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨28, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_29 :
    (∑ i, paf (t103 i) (⟨29, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨29, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_30 :
    (∑ i, paf (t103 i) (⟨30, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨30, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_31 :
    (∑ i, paf (t103 i) (⟨31, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨31, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_32 :
    (∑ i, paf (t103 i) (⟨32, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨32, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_33 :
    (∑ i, paf (t103 i) (⟨33, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨33, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_34 :
    (∑ i, paf (t103 i) (⟨34, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨34, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_35 :
    (∑ i, paf (t103 i) (⟨35, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨35, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_36 :
    (∑ i, paf (t103 i) (⟨36, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨36, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_37 :
    (∑ i, paf (t103 i) (⟨37, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨37, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_38 :
    (∑ i, paf (t103 i) (⟨38, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨38, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_39 :
    (∑ i, paf (t103 i) (⟨39, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨39, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_40 :
    (∑ i, paf (t103 i) (⟨40, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨40, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_41 :
    (∑ i, paf (t103 i) (⟨41, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨41, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_42 :
    (∑ i, paf (t103 i) (⟨42, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨42, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_43 :
    (∑ i, paf (t103 i) (⟨43, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨43, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_44 :
    (∑ i, paf (t103 i) (⟨44, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨44, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_45 :
    (∑ i, paf (t103 i) (⟨45, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨45, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_46 :
    (∑ i, paf (t103 i) (⟨46, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨46, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_47 :
    (∑ i, paf (t103 i) (⟨47, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨47, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_48 :
    (∑ i, paf (t103 i) (⟨48, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨48, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_49 :
    (∑ i, paf (t103 i) (⟨49, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨49, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_50 :
    (∑ i, paf (t103 i) (⟨50, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨50, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_51 :
    (∑ i, paf (t103 i) (⟨51, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨51, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_52 :
    (∑ i, paf (t103 i) (⟨52, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨52, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_53 :
    (∑ i, paf (t103 i) (⟨53, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨53, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_54 :
    (∑ i, paf (t103 i) (⟨54, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨54, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_55 :
    (∑ i, paf (t103 i) (⟨55, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨55, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_56 :
    (∑ i, paf (t103 i) (⟨56, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨56, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_57 :
    (∑ i, paf (t103 i) (⟨57, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨57, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_58 :
    (∑ i, paf (t103 i) (⟨58, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨58, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_59 :
    (∑ i, paf (t103 i) (⟨59, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨59, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_60 :
    (∑ i, paf (t103 i) (⟨60, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨60, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_61 :
    (∑ i, paf (t103 i) (⟨61, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨61, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_62 :
    (∑ i, paf (t103 i) (⟨62, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨62, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_63 :
    (∑ i, paf (t103 i) (⟨63, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨63, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_64 :
    (∑ i, paf (t103 i) (⟨64, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨64, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_65 :
    (∑ i, paf (t103 i) (⟨65, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨65, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_66 :
    (∑ i, paf (t103 i) (⟨66, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨66, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_67 :
    (∑ i, paf (t103 i) (⟨67, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨67, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_68 :
    (∑ i, paf (t103 i) (⟨68, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨68, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_69 :
    (∑ i, paf (t103 i) (⟨69, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨69, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_70 :
    (∑ i, paf (t103 i) (⟨70, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨70, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_71 :
    (∑ i, paf (t103 i) (⟨71, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨71, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_72 :
    (∑ i, paf (t103 i) (⟨72, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨72, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_73 :
    (∑ i, paf (t103 i) (⟨73, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨73, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_74 :
    (∑ i, paf (t103 i) (⟨74, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨74, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_75 :
    (∑ i, paf (t103 i) (⟨75, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨75, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_76 :
    (∑ i, paf (t103 i) (⟨76, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨76, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_77 :
    (∑ i, paf (t103 i) (⟨77, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨77, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_78 :
    (∑ i, paf (t103 i) (⟨78, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨78, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_79 :
    (∑ i, paf (t103 i) (⟨79, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨79, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_80 :
    (∑ i, paf (t103 i) (⟨80, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨80, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_81 :
    (∑ i, paf (t103 i) (⟨81, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨81, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_82 :
    (∑ i, paf (t103 i) (⟨82, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨82, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_83 :
    (∑ i, paf (t103 i) (⟨83, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨83, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_84 :
    (∑ i, paf (t103 i) (⟨84, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨84, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_85 :
    (∑ i, paf (t103 i) (⟨85, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨85, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_86 :
    (∑ i, paf (t103 i) (⟨86, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨86, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_87 :
    (∑ i, paf (t103 i) (⟨87, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨87, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_88 :
    (∑ i, paf (t103 i) (⟨88, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨88, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_89 :
    (∑ i, paf (t103 i) (⟨89, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨89, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_90 :
    (∑ i, paf (t103 i) (⟨90, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨90, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_91 :
    (∑ i, paf (t103 i) (⟨91, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨91, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_92 :
    (∑ i, paf (t103 i) (⟨92, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨92, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_93 :
    (∑ i, paf (t103 i) (⟨93, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨93, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_94 :
    (∑ i, paf (t103 i) (⟨94, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨94, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_95 :
    (∑ i, paf (t103 i) (⟨95, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨95, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_96 :
    (∑ i, paf (t103 i) (⟨96, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨96, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_97 :
    (∑ i, paf (t103 i) (⟨97, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨97, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_98 :
    (∑ i, paf (t103 i) (⟨98, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨98, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_99 :
    (∑ i, paf (t103 i) (⟨99, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨99, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_100 :
    (∑ i, paf (t103 i) (⟨100, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨100, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_101 :
    (∑ i, paf (t103 i) (⟨101, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨101, by decide⟩ : Fin 103) := by
  rfl

private theorem t103_paf_102 :
    (∑ i, paf (t103 i) (⟨102, by decide⟩ : Fin 103)) =
      (103 : ℤ) * deltaZero (⟨102, by decide⟩ : Fin 103) := by
  rfl

/-- Kernel-reduced periodic T-matrix certificate for `t103`. -/
theorem t103_isTMatrixCertificate : IsTMatrixQuadruple t103 := by
  unfold IsTMatrixQuadruple
  refine ⟨t103_entries, t103_support, ?_⟩
  intro s
  fin_cases s
  · exact t103_paf_0
  · exact t103_paf_1
  · exact t103_paf_2
  · exact t103_paf_3
  · exact t103_paf_4
  · exact t103_paf_5
  · exact t103_paf_6
  · exact t103_paf_7
  · exact t103_paf_8
  · exact t103_paf_9
  · exact t103_paf_10
  · exact t103_paf_11
  · exact t103_paf_12
  · exact t103_paf_13
  · exact t103_paf_14
  · exact t103_paf_15
  · exact t103_paf_16
  · exact t103_paf_17
  · exact t103_paf_18
  · exact t103_paf_19
  · exact t103_paf_20
  · exact t103_paf_21
  · exact t103_paf_22
  · exact t103_paf_23
  · exact t103_paf_24
  · exact t103_paf_25
  · exact t103_paf_26
  · exact t103_paf_27
  · exact t103_paf_28
  · exact t103_paf_29
  · exact t103_paf_30
  · exact t103_paf_31
  · exact t103_paf_32
  · exact t103_paf_33
  · exact t103_paf_34
  · exact t103_paf_35
  · exact t103_paf_36
  · exact t103_paf_37
  · exact t103_paf_38
  · exact t103_paf_39
  · exact t103_paf_40
  · exact t103_paf_41
  · exact t103_paf_42
  · exact t103_paf_43
  · exact t103_paf_44
  · exact t103_paf_45
  · exact t103_paf_46
  · exact t103_paf_47
  · exact t103_paf_48
  · exact t103_paf_49
  · exact t103_paf_50
  · exact t103_paf_51
  · exact t103_paf_52
  · exact t103_paf_53
  · exact t103_paf_54
  · exact t103_paf_55
  · exact t103_paf_56
  · exact t103_paf_57
  · exact t103_paf_58
  · exact t103_paf_59
  · exact t103_paf_60
  · exact t103_paf_61
  · exact t103_paf_62
  · exact t103_paf_63
  · exact t103_paf_64
  · exact t103_paf_65
  · exact t103_paf_66
  · exact t103_paf_67
  · exact t103_paf_68
  · exact t103_paf_69
  · exact t103_paf_70
  · exact t103_paf_71
  · exact t103_paf_72
  · exact t103_paf_73
  · exact t103_paf_74
  · exact t103_paf_75
  · exact t103_paf_76
  · exact t103_paf_77
  · exact t103_paf_78
  · exact t103_paf_79
  · exact t103_paf_80
  · exact t103_paf_81
  · exact t103_paf_82
  · exact t103_paf_83
  · exact t103_paf_84
  · exact t103_paf_85
  · exact t103_paf_86
  · exact t103_paf_87
  · exact t103_paf_88
  · exact t103_paf_89
  · exact t103_paf_90
  · exact t103_paf_91
  · exact t103_paf_92
  · exact t103_paf_93
  · exact t103_paf_94
  · exact t103_paf_95
  · exact t103_paf_96
  · exact t103_paf_97
  · exact t103_paf_98
  · exact t103_paf_99
  · exact t103_paf_100
  · exact t103_paf_101
  · exact t103_paf_102

private theorem t163_entries : ∀ i q, IsTEntry (t163 i q) := by
  decide

private theorem t163_support : ∀ q, supportCount t163 q = 1 := by
  decide

private theorem t163_paf_0 :
    (∑ i, paf (t163 i) (⟨0, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨0, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_1 :
    (∑ i, paf (t163 i) (⟨1, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨1, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_2 :
    (∑ i, paf (t163 i) (⟨2, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨2, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_3 :
    (∑ i, paf (t163 i) (⟨3, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨3, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_4 :
    (∑ i, paf (t163 i) (⟨4, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨4, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_5 :
    (∑ i, paf (t163 i) (⟨5, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨5, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_6 :
    (∑ i, paf (t163 i) (⟨6, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨6, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_7 :
    (∑ i, paf (t163 i) (⟨7, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨7, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_8 :
    (∑ i, paf (t163 i) (⟨8, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨8, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_9 :
    (∑ i, paf (t163 i) (⟨9, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨9, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_10 :
    (∑ i, paf (t163 i) (⟨10, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨10, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_11 :
    (∑ i, paf (t163 i) (⟨11, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨11, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_12 :
    (∑ i, paf (t163 i) (⟨12, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨12, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_13 :
    (∑ i, paf (t163 i) (⟨13, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨13, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_14 :
    (∑ i, paf (t163 i) (⟨14, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨14, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_15 :
    (∑ i, paf (t163 i) (⟨15, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨15, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_16 :
    (∑ i, paf (t163 i) (⟨16, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨16, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_17 :
    (∑ i, paf (t163 i) (⟨17, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨17, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_18 :
    (∑ i, paf (t163 i) (⟨18, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨18, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_19 :
    (∑ i, paf (t163 i) (⟨19, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨19, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_20 :
    (∑ i, paf (t163 i) (⟨20, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨20, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_21 :
    (∑ i, paf (t163 i) (⟨21, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨21, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_22 :
    (∑ i, paf (t163 i) (⟨22, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨22, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_23 :
    (∑ i, paf (t163 i) (⟨23, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨23, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_24 :
    (∑ i, paf (t163 i) (⟨24, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨24, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_25 :
    (∑ i, paf (t163 i) (⟨25, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨25, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_26 :
    (∑ i, paf (t163 i) (⟨26, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨26, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_27 :
    (∑ i, paf (t163 i) (⟨27, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨27, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_28 :
    (∑ i, paf (t163 i) (⟨28, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨28, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_29 :
    (∑ i, paf (t163 i) (⟨29, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨29, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_30 :
    (∑ i, paf (t163 i) (⟨30, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨30, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_31 :
    (∑ i, paf (t163 i) (⟨31, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨31, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_32 :
    (∑ i, paf (t163 i) (⟨32, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨32, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_33 :
    (∑ i, paf (t163 i) (⟨33, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨33, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_34 :
    (∑ i, paf (t163 i) (⟨34, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨34, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_35 :
    (∑ i, paf (t163 i) (⟨35, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨35, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_36 :
    (∑ i, paf (t163 i) (⟨36, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨36, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_37 :
    (∑ i, paf (t163 i) (⟨37, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨37, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_38 :
    (∑ i, paf (t163 i) (⟨38, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨38, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_39 :
    (∑ i, paf (t163 i) (⟨39, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨39, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_40 :
    (∑ i, paf (t163 i) (⟨40, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨40, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_41 :
    (∑ i, paf (t163 i) (⟨41, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨41, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_42 :
    (∑ i, paf (t163 i) (⟨42, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨42, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_43 :
    (∑ i, paf (t163 i) (⟨43, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨43, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_44 :
    (∑ i, paf (t163 i) (⟨44, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨44, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_45 :
    (∑ i, paf (t163 i) (⟨45, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨45, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_46 :
    (∑ i, paf (t163 i) (⟨46, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨46, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_47 :
    (∑ i, paf (t163 i) (⟨47, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨47, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_48 :
    (∑ i, paf (t163 i) (⟨48, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨48, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_49 :
    (∑ i, paf (t163 i) (⟨49, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨49, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_50 :
    (∑ i, paf (t163 i) (⟨50, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨50, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_51 :
    (∑ i, paf (t163 i) (⟨51, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨51, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_52 :
    (∑ i, paf (t163 i) (⟨52, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨52, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_53 :
    (∑ i, paf (t163 i) (⟨53, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨53, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_54 :
    (∑ i, paf (t163 i) (⟨54, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨54, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_55 :
    (∑ i, paf (t163 i) (⟨55, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨55, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_56 :
    (∑ i, paf (t163 i) (⟨56, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨56, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_57 :
    (∑ i, paf (t163 i) (⟨57, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨57, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_58 :
    (∑ i, paf (t163 i) (⟨58, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨58, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_59 :
    (∑ i, paf (t163 i) (⟨59, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨59, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_60 :
    (∑ i, paf (t163 i) (⟨60, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨60, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_61 :
    (∑ i, paf (t163 i) (⟨61, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨61, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_62 :
    (∑ i, paf (t163 i) (⟨62, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨62, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_63 :
    (∑ i, paf (t163 i) (⟨63, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨63, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_64 :
    (∑ i, paf (t163 i) (⟨64, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨64, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_65 :
    (∑ i, paf (t163 i) (⟨65, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨65, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_66 :
    (∑ i, paf (t163 i) (⟨66, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨66, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_67 :
    (∑ i, paf (t163 i) (⟨67, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨67, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_68 :
    (∑ i, paf (t163 i) (⟨68, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨68, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_69 :
    (∑ i, paf (t163 i) (⟨69, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨69, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_70 :
    (∑ i, paf (t163 i) (⟨70, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨70, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_71 :
    (∑ i, paf (t163 i) (⟨71, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨71, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_72 :
    (∑ i, paf (t163 i) (⟨72, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨72, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_73 :
    (∑ i, paf (t163 i) (⟨73, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨73, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_74 :
    (∑ i, paf (t163 i) (⟨74, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨74, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_75 :
    (∑ i, paf (t163 i) (⟨75, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨75, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_76 :
    (∑ i, paf (t163 i) (⟨76, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨76, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_77 :
    (∑ i, paf (t163 i) (⟨77, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨77, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_78 :
    (∑ i, paf (t163 i) (⟨78, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨78, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_79 :
    (∑ i, paf (t163 i) (⟨79, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨79, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_80 :
    (∑ i, paf (t163 i) (⟨80, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨80, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_81 :
    (∑ i, paf (t163 i) (⟨81, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨81, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_82 :
    (∑ i, paf (t163 i) (⟨82, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨82, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_83 :
    (∑ i, paf (t163 i) (⟨83, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨83, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_84 :
    (∑ i, paf (t163 i) (⟨84, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨84, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_85 :
    (∑ i, paf (t163 i) (⟨85, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨85, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_86 :
    (∑ i, paf (t163 i) (⟨86, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨86, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_87 :
    (∑ i, paf (t163 i) (⟨87, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨87, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_88 :
    (∑ i, paf (t163 i) (⟨88, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨88, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_89 :
    (∑ i, paf (t163 i) (⟨89, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨89, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_90 :
    (∑ i, paf (t163 i) (⟨90, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨90, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_91 :
    (∑ i, paf (t163 i) (⟨91, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨91, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_92 :
    (∑ i, paf (t163 i) (⟨92, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨92, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_93 :
    (∑ i, paf (t163 i) (⟨93, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨93, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_94 :
    (∑ i, paf (t163 i) (⟨94, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨94, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_95 :
    (∑ i, paf (t163 i) (⟨95, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨95, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_96 :
    (∑ i, paf (t163 i) (⟨96, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨96, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_97 :
    (∑ i, paf (t163 i) (⟨97, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨97, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_98 :
    (∑ i, paf (t163 i) (⟨98, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨98, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_99 :
    (∑ i, paf (t163 i) (⟨99, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨99, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_100 :
    (∑ i, paf (t163 i) (⟨100, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨100, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_101 :
    (∑ i, paf (t163 i) (⟨101, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨101, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_102 :
    (∑ i, paf (t163 i) (⟨102, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨102, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_103 :
    (∑ i, paf (t163 i) (⟨103, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨103, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_104 :
    (∑ i, paf (t163 i) (⟨104, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨104, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_105 :
    (∑ i, paf (t163 i) (⟨105, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨105, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_106 :
    (∑ i, paf (t163 i) (⟨106, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨106, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_107 :
    (∑ i, paf (t163 i) (⟨107, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨107, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_108 :
    (∑ i, paf (t163 i) (⟨108, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨108, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_109 :
    (∑ i, paf (t163 i) (⟨109, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨109, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_110 :
    (∑ i, paf (t163 i) (⟨110, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨110, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_111 :
    (∑ i, paf (t163 i) (⟨111, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨111, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_112 :
    (∑ i, paf (t163 i) (⟨112, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨112, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_113 :
    (∑ i, paf (t163 i) (⟨113, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨113, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_114 :
    (∑ i, paf (t163 i) (⟨114, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨114, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_115 :
    (∑ i, paf (t163 i) (⟨115, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨115, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_116 :
    (∑ i, paf (t163 i) (⟨116, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨116, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_117 :
    (∑ i, paf (t163 i) (⟨117, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨117, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_118 :
    (∑ i, paf (t163 i) (⟨118, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨118, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_119 :
    (∑ i, paf (t163 i) (⟨119, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨119, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_120 :
    (∑ i, paf (t163 i) (⟨120, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨120, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_121 :
    (∑ i, paf (t163 i) (⟨121, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨121, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_122 :
    (∑ i, paf (t163 i) (⟨122, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨122, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_123 :
    (∑ i, paf (t163 i) (⟨123, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨123, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_124 :
    (∑ i, paf (t163 i) (⟨124, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨124, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_125 :
    (∑ i, paf (t163 i) (⟨125, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨125, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_126 :
    (∑ i, paf (t163 i) (⟨126, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨126, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_127 :
    (∑ i, paf (t163 i) (⟨127, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨127, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_128 :
    (∑ i, paf (t163 i) (⟨128, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨128, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_129 :
    (∑ i, paf (t163 i) (⟨129, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨129, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_130 :
    (∑ i, paf (t163 i) (⟨130, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨130, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_131 :
    (∑ i, paf (t163 i) (⟨131, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨131, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_132 :
    (∑ i, paf (t163 i) (⟨132, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨132, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_133 :
    (∑ i, paf (t163 i) (⟨133, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨133, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_134 :
    (∑ i, paf (t163 i) (⟨134, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨134, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_135 :
    (∑ i, paf (t163 i) (⟨135, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨135, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_136 :
    (∑ i, paf (t163 i) (⟨136, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨136, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_137 :
    (∑ i, paf (t163 i) (⟨137, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨137, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_138 :
    (∑ i, paf (t163 i) (⟨138, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨138, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_139 :
    (∑ i, paf (t163 i) (⟨139, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨139, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_140 :
    (∑ i, paf (t163 i) (⟨140, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨140, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_141 :
    (∑ i, paf (t163 i) (⟨141, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨141, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_142 :
    (∑ i, paf (t163 i) (⟨142, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨142, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_143 :
    (∑ i, paf (t163 i) (⟨143, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨143, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_144 :
    (∑ i, paf (t163 i) (⟨144, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨144, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_145 :
    (∑ i, paf (t163 i) (⟨145, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨145, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_146 :
    (∑ i, paf (t163 i) (⟨146, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨146, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_147 :
    (∑ i, paf (t163 i) (⟨147, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨147, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_148 :
    (∑ i, paf (t163 i) (⟨148, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨148, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_149 :
    (∑ i, paf (t163 i) (⟨149, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨149, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_150 :
    (∑ i, paf (t163 i) (⟨150, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨150, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_151 :
    (∑ i, paf (t163 i) (⟨151, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨151, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_152 :
    (∑ i, paf (t163 i) (⟨152, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨152, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_153 :
    (∑ i, paf (t163 i) (⟨153, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨153, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_154 :
    (∑ i, paf (t163 i) (⟨154, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨154, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_155 :
    (∑ i, paf (t163 i) (⟨155, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨155, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_156 :
    (∑ i, paf (t163 i) (⟨156, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨156, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_157 :
    (∑ i, paf (t163 i) (⟨157, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨157, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_158 :
    (∑ i, paf (t163 i) (⟨158, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨158, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_159 :
    (∑ i, paf (t163 i) (⟨159, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨159, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_160 :
    (∑ i, paf (t163 i) (⟨160, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨160, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_161 :
    (∑ i, paf (t163 i) (⟨161, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨161, by decide⟩ : Fin 163) := by
  rfl

private theorem t163_paf_162 :
    (∑ i, paf (t163 i) (⟨162, by decide⟩ : Fin 163)) =
      (163 : ℤ) * deltaZero (⟨162, by decide⟩ : Fin 163) := by
  rfl

/-- Kernel-reduced periodic T-matrix certificate for `t163`. -/
theorem t163_isTMatrixCertificate : IsTMatrixQuadruple t163 := by
  unfold IsTMatrixQuadruple
  refine ⟨t163_entries, t163_support, ?_⟩
  intro s
  fin_cases s
  · exact t163_paf_0
  · exact t163_paf_1
  · exact t163_paf_2
  · exact t163_paf_3
  · exact t163_paf_4
  · exact t163_paf_5
  · exact t163_paf_6
  · exact t163_paf_7
  · exact t163_paf_8
  · exact t163_paf_9
  · exact t163_paf_10
  · exact t163_paf_11
  · exact t163_paf_12
  · exact t163_paf_13
  · exact t163_paf_14
  · exact t163_paf_15
  · exact t163_paf_16
  · exact t163_paf_17
  · exact t163_paf_18
  · exact t163_paf_19
  · exact t163_paf_20
  · exact t163_paf_21
  · exact t163_paf_22
  · exact t163_paf_23
  · exact t163_paf_24
  · exact t163_paf_25
  · exact t163_paf_26
  · exact t163_paf_27
  · exact t163_paf_28
  · exact t163_paf_29
  · exact t163_paf_30
  · exact t163_paf_31
  · exact t163_paf_32
  · exact t163_paf_33
  · exact t163_paf_34
  · exact t163_paf_35
  · exact t163_paf_36
  · exact t163_paf_37
  · exact t163_paf_38
  · exact t163_paf_39
  · exact t163_paf_40
  · exact t163_paf_41
  · exact t163_paf_42
  · exact t163_paf_43
  · exact t163_paf_44
  · exact t163_paf_45
  · exact t163_paf_46
  · exact t163_paf_47
  · exact t163_paf_48
  · exact t163_paf_49
  · exact t163_paf_50
  · exact t163_paf_51
  · exact t163_paf_52
  · exact t163_paf_53
  · exact t163_paf_54
  · exact t163_paf_55
  · exact t163_paf_56
  · exact t163_paf_57
  · exact t163_paf_58
  · exact t163_paf_59
  · exact t163_paf_60
  · exact t163_paf_61
  · exact t163_paf_62
  · exact t163_paf_63
  · exact t163_paf_64
  · exact t163_paf_65
  · exact t163_paf_66
  · exact t163_paf_67
  · exact t163_paf_68
  · exact t163_paf_69
  · exact t163_paf_70
  · exact t163_paf_71
  · exact t163_paf_72
  · exact t163_paf_73
  · exact t163_paf_74
  · exact t163_paf_75
  · exact t163_paf_76
  · exact t163_paf_77
  · exact t163_paf_78
  · exact t163_paf_79
  · exact t163_paf_80
  · exact t163_paf_81
  · exact t163_paf_82
  · exact t163_paf_83
  · exact t163_paf_84
  · exact t163_paf_85
  · exact t163_paf_86
  · exact t163_paf_87
  · exact t163_paf_88
  · exact t163_paf_89
  · exact t163_paf_90
  · exact t163_paf_91
  · exact t163_paf_92
  · exact t163_paf_93
  · exact t163_paf_94
  · exact t163_paf_95
  · exact t163_paf_96
  · exact t163_paf_97
  · exact t163_paf_98
  · exact t163_paf_99
  · exact t163_paf_100
  · exact t163_paf_101
  · exact t163_paf_102
  · exact t163_paf_103
  · exact t163_paf_104
  · exact t163_paf_105
  · exact t163_paf_106
  · exact t163_paf_107
  · exact t163_paf_108
  · exact t163_paf_109
  · exact t163_paf_110
  · exact t163_paf_111
  · exact t163_paf_112
  · exact t163_paf_113
  · exact t163_paf_114
  · exact t163_paf_115
  · exact t163_paf_116
  · exact t163_paf_117
  · exact t163_paf_118
  · exact t163_paf_119
  · exact t163_paf_120
  · exact t163_paf_121
  · exact t163_paf_122
  · exact t163_paf_123
  · exact t163_paf_124
  · exact t163_paf_125
  · exact t163_paf_126
  · exact t163_paf_127
  · exact t163_paf_128
  · exact t163_paf_129
  · exact t163_paf_130
  · exact t163_paf_131
  · exact t163_paf_132
  · exact t163_paf_133
  · exact t163_paf_134
  · exact t163_paf_135
  · exact t163_paf_136
  · exact t163_paf_137
  · exact t163_paf_138
  · exact t163_paf_139
  · exact t163_paf_140
  · exact t163_paf_141
  · exact t163_paf_142
  · exact t163_paf_143
  · exact t163_paf_144
  · exact t163_paf_145
  · exact t163_paf_146
  · exact t163_paf_147
  · exact t163_paf_148
  · exact t163_paf_149
  · exact t163_paf_150
  · exact t163_paf_151
  · exact t163_paf_152
  · exact t163_paf_153
  · exact t163_paf_154
  · exact t163_paf_155
  · exact t163_paf_156
  · exact t163_paf_157
  · exact t163_paf_158
  · exact t163_paf_159
  · exact t163_paf_160
  · exact t163_paf_161
  · exact t163_paf_162

end HadamardFormal.Data
